export const PERMISSIONS = [
  { id: 64, name: "create", module: "board", displayName: "Create Board" },
  { id: 65, name: "list", module: "board", displayName: "List Board" },
  { id: 66, name: "update", module: "board", displayName: "Update Board" },
  { id: 67, name: "delete", module: "board", displayName: "Delete Board" },
  { id: 68, name: "detail", module: "board", displayName: "Detail Board" },
  { id: 69, name: "add_member", module: "board", displayName: "Add Member to Board" },
  { id: 70, name: "remove_member", module: "board", displayName: "Remove Member from Board" },
  { id: 71, name: "update_member", module: "board", displayName: "Update Board Member" },
  { id: 72, name: "list_member", module: "board", displayName: "List Board Members" },
  // list
  { id: 73, name: "create", module: "list", displayName: "Create List" },
  { id: 74, name: "list", module: "list", displayName: "List Lists" },
  { id: 75, name: "update", module: "list", displayName: "Update List" },
  { id: 76, name: "delete", module: "list", displayName: "Delete List" },
  { id: 77, name: "detail", module: "list", displayName: "Detail List" },
  { id: 78, name: "add_member", module: "list", displayName: "Add Member to List" },
  { id: 79, name: "remove_member", module: "list", displayName: "Remove Member from List" },
  { id: 80, name: "update_member", module: "list", displayName: "Update List Member" },
  { id: 81, name: "list_member", module: "list", displayName: "List List Members" },
  // card
  { id: 82, name: "create", module: "card", displayName: "Create Card" },
  { id: 83, name: "list", module: "card", displayName: "List Cards" },
  { id: 84, name: "update", module: "card", displayName: "Update Card" },
  { id: 85, name: "delete", module: "card", displayName: "Delete Card" },
  { id: 86, name: "detail", module: "card", displayName: "Detail Card" },
  { id: 87, name: "add_member", module: "card", displayName: "Add Member to Card" },
  { id: 88, name: "remove_member", module: "card", displayName: "Remove Member from Card" },
  { id: 89, name: "update_member", module: "card", displayName: "Update Card Member" },
  { id: 90, name: "list_member", module: "card", displayName: "List Card Members" },
  { id: 91, name: "create", module: "comment", displayName: "Create Comment" },
  { id: 92, name: "list", module: "comment", displayName: "List Comments" },
  { id: 93, name: "update", module: "comment", displayName: "Update Comment" },
  { id: 94, name: "delete", module: "comment", displayName: "Delete Comment" },
  { id: 95, name: "detail", module: "comment", displayName: "Detail Comment" },
  { id: 96, name: "add_member", module: "comment", displayName: "Add Member to Comment" },
  { id: 97, name: "remove_member", module: "comment", displayName: "Remove Member from Comment" },
  { id: 98, name: "update_member", module: "comment", displayName: "Update Comment Member" },
  { id: 99, name: "list_member", module: "comment", displayName: "List Comment Members" },
  { id: 100, name: "create", module: "tag", displayName: "Create Tag" },
  { id: 101, name: "list", module: "tag", displayName: "List Tags" },
  { id: 102, name: "update", module: "tag", displayName: "Update Tag" },
  { id: 103, name: "delete", module: "tag", displayName: "Delete Tag" },
  { id: 104, name: "detail", module: "tag", displayName: "Detail Tag" },
  { id: 105, name: "add_member", module: "tag", displayName: "Add Member to Tag" },
  { id: 106, name: "remove_member", module: "tag", displayName: "Remove Member from Tag" },
  { id: 107, name: "update_member", module: "tag", displayName: "Update Tag Member" },
  { id: 108, name: "list_member", module: "tag", displayName: "List Tag Members" }
];
